//DEFINES
#define READBIT(WORD,BIT) ((WORD>>BIT)&1)
#define WRITENIBBLE(WORD,NIBBLESTARTBITPOS,VAL) \
WORD=((WORD&~(15<<NIBBLESTARTBITPOS))|(VAL<<NIBBLESTARTBITPOS))
#define READNIBBLE(WORD,NIBBLESTARTBIT) \
((WORD>>NIBBLESTARTBIT)&15)
#define WRITEBYTE(WORD,BYTESTARTBITPOS,VAL) \
WORD=((WORD&~(0XFF<<BYTESTARTBITPOS))|((VAL<<BYTESTARTBITPOS)))
#define WRITEBIT(WORD,BITPOS,BITVAL) \
WORD=((WORD&~(1<<BITPOS))|(BITVAL<<BITPOS))
